# see https://travis-ci.community/t/older-perl-version-stopped-working/4294
dist: trusty
language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.24"
  - "5.22"
  - "5.20"

install:
   - cpanm --quiet --notest Dist::Zilla
   - "dzil authordeps --missing | cpanm --notest"
   - "dzil listdeps --missing | grep -v Fuse | cpanm --notest"

script:
  - dzil smoke --release --author
